<a href="https://colab.research.google.com/github/ngthvan02/AI/blob/main/ANN(20_03_2023).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
from sklearn.linear_model import Perceptron
x=[[0,0],[0,1],[1,0],[1,1]]
t=[0,1,1,1]

In [56]:
model=Perceptron()
model.fit(x,t)
model.score(x,t)

1.0

In [57]:
x1=[[0.5,-1],[0.5,0.5],[-10,1]]
y1=model.predict(x1)
model.score(x1,y1)

1.0

In [58]:
from sklearn.linear_model import Perceptron
a=[[-0.5,-0.5],[-0.5,-0.5],[0.3,-0.5],[-0.1,1]]
b=[1,1,0,0]
model=Perceptron()
model.fit(a,b)
model.score(a,b)

1.0

In [59]:
a1=[[0.4,1],[0.1,-0.5],[0.2,-0.9],[1,-0.2]]
y2=model.predict(a1)
model.score(a1,y2)

1.0

In [60]:
from sklearn import datasets
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt

In [61]:
from numpy.core.fromnumeric import shape
iris=datasets.load_iris()
shape(iris)
print(iris)




{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [63]:

X=iris.data
y=iris.target
print(X[:5])
print(y[:5])
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)
sc=StandardScaler()
sc.fit(X_train)
X_train_std=sc.transform(X_train)

X_test_std=sc.transform(X_test)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


In [66]:

model=Perceptron(max_iter=40,eta0=0.1,random_state=0)
model.fit(X_train_std,y_train)
y_prd=model.predict(X_test_std)
print(y_prd)
print(y_test)
print('Do chinh xac trung binh:',accuracy_score(y_test,y_prd))




[2 2 2 0 2 0 2 2 0 1 0 2 2 0 0 1 2 1 0 2 0 2 0 0 1 0 2 2 0 0 2 2 1 1 0 1 1
 0 0 1 2 2 1 2 1]
[1 2 2 0 2 0 1 2 0 1 0 2 2 0 0 1 2 1 0 2 0 2 0 0 1 0 2 2 0 0 2 2 1 1 0 1 1
 0 0 1 2 2 1 2 1]
Do chinh xac trung binh: 0.9555555555555556
